# Generated by Django 5.2.1 on 2025-06-28 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('iso_code', models.CharField(help_text='ISO 3166-1 A2 CODE of country', max_length=2)),
                ('continent', models.CharField(blank=True, max_length=50)),
                ('capital', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('language', models.CharField(blank=True, max_length=15)),
                ('best_time_to_visit', models.CharField(blank=True, help_text='Best month to visit this country.', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='A date in YYYY-MM-DD format.')),
                ('end_date', models.DateField(help_text='A date in YYYY-MM-DD format.')),
                ('available_spots', models.PositiveIntegerField()),
                ('price_adjustment', models.DecimalField(decimal_places=2, max_digits=3)),
                ('status', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited'), ('sold_out', 'Sold_out'), ('cancelled', 'Cancelled')], default='available', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('is_popular', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.country')),
            ],
        ),
    ]
