# Generated by Django 5.2.1 on 2025-06-28 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_author'),
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('description', models.TextField()),
                ('max_participants', models.PositiveIntegerField()),
                ('difficulty_level', models.CharField(blank=True, max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('status', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited'), ('sold_out', 'Sold_out'), ('cancelled', 'Cancelled')], default='available', max_length=12)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.author')),
                ('destination', models.ManyToManyField(to='tours.destination')),
                ('tourist', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
