# Generated by Django 5.2.1 on 2025-07-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(help_text='ISO 3166-1 A2 CODE of country', max_length=3),
        ),
    ]
