# Generated by Django 5.2.1 on 2025-07-02 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_country_options_date_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='destination',
        ),
        migrations.AddField(
            model_name='destination',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tours.tour'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='date',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.RemoveField(
            model_name='date',
            name='tour',
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AddField(
            model_name='date',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.tour'),
            preserve_default=False,
        ),
    ]
