# Generated by Django 5.2.1 on 2025-07-03 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_author'),
        ('tours', '0005_remove_tour_destination_destination_tour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='tours.tour'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='tours.country'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='tours.tour'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='accounts.author'),
        ),
    ]
