# Generated by Django 5.2.1 on 2025-07-04 14:49

import apps.tours.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_alter_date_tour_alter_destination_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='available_spots',
        ),
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(help_text='ISO 3166-1 A2 CODE of country', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_people', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('sepa', 'On IBAN'), ('cash', 'Cash'), ('paypal', 'Paypal')], max_length=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('failed', 'Fail'), ('refunded', 'Refund')], max_length=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='tours.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=apps.tours.models.media.image_upload_path)),
                ('type', models.CharField(choices=[('main', 'Main Photo(1)'), ('gallery', 'Gallery(5)'), ('slide', 'Slide(n)')], max_length=7)),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Caption')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tours.tour')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('type', 'main')), fields=('tour', 'type'), name='unique_main_photo')],
            },
        ),
    ]
