# Generated by Django 5.2.1 on 2025-07-04 22:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_remove_date_available_spots_tour_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.AlterField(
            model_name='tour',
            name='difficulty_level',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tourist',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
