# Generated by Django 5.2.1 on 2025-07-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_remove_payment_booking_alter_tour_difficulty_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='country',
        ),
    ]
