# Generated by Django 5.2.1 on 2025-07-06 18:31

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_remove_tour_country_alter_tour_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(default=1, upload_to='countries/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='image_hero',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='countries'),
            preserve_default=False,
        ),
    ]
