# Generated by Django 5.2.1 on 2025-07-07 16:51

import apps.tours.models.country
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_country_image_country_image_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(upload_to=apps.tours.models.country.image_upload_path),
        ),
        migrations.AlterField(
            model_name='country',
            name='image_hero',
            field=imagekit.models.fields.ProcessedImageField(upload_to=apps.tours.models.country.image_upload_path),
        ),
    ]
