# Generated by Django 5.2.1 on 2025-07-11 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_alter_country_image_alter_country_image_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='tour',
        ),
        migrations.AddField(
            model_name='destination',
            name='_category',
            field=models.CharField(choices=[('historical', 'Historical'), ('cultural', 'Cultural'), ('adventure', 'Adventure'), ('beach', 'Beach'), ('urban', 'Urban'), ('luxury', 'Luxury'), ('custom', 'Custom')], default='historical', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='_custom_category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='average_temp',
            field=models.CharField(default='15-25°C', help_text='15-25°C', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(default='Description text field'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='time_zone',
            field=models.CharField(default='UTC+0', help_text='UTC+0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='destinations',
            field=models.ManyToManyField(related_name='tours', to='tours.destination'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(choices=[('europe', 'Europe'), ('asia', 'Asia'), ('north_america', 'North America'), ('south_america', 'South America'), ('africa', 'Africa'), ('oceania', 'Oceania')], max_length=20),
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('destination', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='tours.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=16)),
                ('weather_info', models.TextField()),
                ('destination', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='tours.destination')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('destination', 'season'), name='unique_weather_season')],
            },
        ),
    ]
