# Generated by Django 5.2.1 on 2025-07-12 18:17

import apps.tours.models.destination
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_remove_destination_tour_destination__category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='best_time_to_visit',
        ),
        migrations.AddField(
            model_name='destination',
            name='best_time_to_visit',
            field=models.CharField(blank=True, help_text='Best month to visit this destination.', max_length=260),
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(default='some url', upload_to=apps.tours.models.destination.image_upload_path),
            preserve_default=False,
        ),
    ]
