version: "3.9"

services:
  app:
    build:
      context: backend/
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app
      - my_media:/files/media
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine3.20
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - my_db:$PGDATA

  ui:
    build:
      context: frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/app
    command: >
      sh -c "npm run dev"
    env_file:
      - .env
    depends_on:
      - app
    

volumes:
  my_db:
  my_media: