# Generated by Django 5.2.1 on 2025-06-28 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_verified_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False, help_text='Verification status')),
                ('profession', models.CharField(blank=True, help_text="The author's profession or primary occupation.", max_length=100)),
                ('bio', models.TextField(blank=True, help_text='A short biography of the author.')),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Number of years of writing/travel experience.')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating of the author (e.g., from reviews).', max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0, help_text='Total number of reviews received by the author.')),
                ('languages', models.JSONField(blank=True, default=list, help_text="List of languages the author is proficient in (e.g., ['English', 'Spanish']).")),
                ('speciality', models.JSONField(blank=True, default=list, help_text="List of writing/travel specialties (e.g., ['Adventure Travel', 'Historical Fiction']).")),
                ('social_media', models.JSONField(blank=True, default=list, help_text="Dictionary of social media links (e.g., {'instagram': 'link', 'twitter': 'link'}).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The user associated with this author profile.', on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
    ]
