# Generated by Django 5.2.1 on 2025-07-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='direct_contact',
            field=models.CharField(default=4353245342523, help_text='The Author contact Ex: Whatsapp, TG or any direct link', max_length=420),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='phone_number',
            field=models.CharField(default=4564536325325, max_length=60),
            preserve_default=False,
        ),
    ]
