# Generated by Django 5.2.1 on 2025-07-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
